name: Build Transmission 4.1.0-beta.2 static (aarch64) on Ubuntu 22.04

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      PREFIX: ${{ github.workspace }}/build
      PATH: ${{ github.workspace }}/build/bin:${{ env.PATH }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential autoconf automake libtool pkg-config \
            curl wget tar unzip xz-utils git \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
            binutils-aarch64-linux-gnu

      - name: Prepare directories
        run: |
          mkdir -p sources build

      - name: Download sources if missing
        run: |
          cd sources
          [ -f zlib-1.2.13.tar.gz ] || curl -LO https://zlib.net/zlib-1.2.13.tar.gz
          [ -f libevent-2.1.12-stable.tar.gz ] || curl -LO https://github.com/libevent/libevent/releases/download/release-2.1.12-stable/libevent-2.1.12-stable.tar.gz
          [ -f openssl-3.1.3.tar.gz ] || curl -LO https://www.openssl.org/source/openssl-3.1.3.tar.gz
          [ -f curl-8.2.1.tar.gz ] || curl -LO https://curl.se/download/curl-8.2.1.tar.gz
          [ -f transmission-4.1.0-beta.2.tar.gz ] || curl -LO https://github.com/transmission/transmission/archive/refs/tags/4.1.0-beta.2.tar.gz

      - name: Build zlib (static)
        run: |
          cd build
          if [ ! -d zlib-1.2.13 ]; then
            tar xf ../sources/zlib-1.2.13.tar.gz
          fi
          cd zlib-1.2.13
          CC=aarch64-linux-gnu-gcc ./configure --static --prefix=$PREFIX
          make -j$(nproc)
          make install

      - name: Build libevent (static)
        run: |
          cd build
          if [ ! -d libevent-2.1.12-stable ]; then
            tar xf ../sources/libevent-2.1.12-stable.tar.gz
          fi
          cd libevent-2.1.12-stable
          ./configure --host=aarch64-linux-gnu --prefix=$PREFIX --disable-shared --enable-static
          make -j$(nproc)
          make install

      - name: Build OpenSSL (static)
        run: |
          cd build
          if [ ! -d openssl-3.1.3 ]; then
            tar xf ../sources/openssl-3.1.3.tar.gz
          fi
          cd openssl-3.1.3
          ./Configure linux-aarch64 no-shared no-tests --prefix=$PREFIX
          make -j$(nproc)
          make install_sw

      - name: Build libcurl (static)
        run: |
          cd build
          if [ ! -d curl-8.2.1 ]; then
            tar xf ../sources/curl-8.2.1.tar.gz
          fi
          cd curl-8.2.1
          ./configure --host=aarch64-linux-gnu --prefix=$PREFIX --disable-shared --enable-static \
            --with-ssl=$PREFIX --with-zlib=$PREFIX
          make -j$(nproc)
          make install

      - name: Extract Transmission source
        run: |
          if [ ! -d transmission ]; then
            tar xf sources/transmission-4.1.0-beta.2.tar.gz
            mv transmission-4.1.0-beta.2 transmission
          fi

      - name: Build Transmission static
        run: |
          cd transmission
          ./autogen.sh
          CC=aarch64-linux-gnu-gcc \
          CXX=aarch64-linux-gnu-g++ \
          PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig \
          ./configure --host=aarch64-linux-gnu --prefix=$PREFIX \
            --disable-shared --enable-static \
            --with-libevent=$PREFIX \
            --with-openssl=$PREFIX \
            --with-libcurl=$PREFIX \
            --with-zlib=$PREFIX \
            --without-gtk --without-qt
          make clean
          make LDFLAGS="-static -L$PREFIX/lib" -j$(nproc)

      - name: Strip and show size
        run: |
          aarch64-linux-gnu-strip src/transmission-daemon src/transmission-cli
          aarch64-linux-gnu-size src/transmission-daemon src/transmission-cli

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: transmission-static-aarch64
          path: |
            transmission/src/transmission-daemon
            transmission/src/transmission-cli
