name: Build Transmission 4.1.0-beta2 for Aarch64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU for Aarch64
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and run in Aarch64 container
      run: |
        docker run --rm -v $(pwd):/workspace --platform linux/arm64 ubuntu:22.04 bash -c "
          apt-get update && apt-get install -y \
            build-essential \
            cmake \
            libssl-dev \
            libcurl4-openssl-dev \
            libevent-dev \
            pkg-config \
            wget \
            xz-utils

          wget https://github.com/transmission/transmission/releases/download/4.1.0-beta2/transmission-4.1.0-beta2.tar.xz
          tar -xf transmission-4.1.0-beta2.tar.xz
          cd transmission-4.1.0-beta2

          mkdir build
          cd build

          cmake -DTRANSMISSION_DAEMON_STATIC=ON \
                -DTRANSMISSION_CLI_STATIC=ON \
                -DTRANSMISSION_GTK_STATIC=ON \
                -DCMAKE_BUILD_TYPE=Release \
                ..

          make -j$(nproc)
          
          cp daemon/transmission-daemon /workspace/
          cp cli/transmission-remote /workspace/
          cp cli/transmission-show /workspace/
          cp cli/transmission-edit /workspace/
          cp cli/transmission-create /workspace/
        "

    - name: Archive static binaries
      uses: actions/upload-artifact@v4
      with:
        name: transmission-4.1.0-beta2-aarch64-static
        path: |
          transmission-daemon
          transmission-remote
          transmission-show
          transmission-edit
          transmission-create
